version: '2.7'
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - /home/fjavidcr/docker/radarr/config:/config
      - /media/fjavidcr/wd5001/movies:/media/fjavidcr/wd5001/movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - /home/fjavidcr/docker/sonarr/config:/config
      - /media/fjavidcr/wd5001/series:/media/fjavidcr/wd5001/series
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid

  jackett:
    image: linuxserver/jackett
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - /home/fjavidcr/docker/jackett/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid

  # lidarr:
  #   image: linuxserver/lidarr
  #   container_name: lidarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Madrid
  #   volumes:
  #     - /home/fjavidcr/docker/lidarr/config:/config
  #     - /media/fjavidcr/wd500/torrentbox/multimedia/lidarr:/mnt/multimedia
  #     - /media/fjavidcr/wd500/tmp:/media/fjavidcr/wd500/tmp
  #   ports:
  #     - 8686:8686
  #   restart: unless-stopped

  # ombi:
  #   image: linuxserver/ombi
  #   container_name: ombi
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Madrid
  #     - BASE_URL=/ #optional
  #   volumes:
  #     - /home/fjavidcr/docker/ombi/config:/config
  #   ports:
  #     - 3579:3579
  #   restart: unless-stopped

# volumes:
#   /home/fjavidcr/docker/radarr/config:
#     name: radarr
#   /home/fjavidcr/docker/sonarr/config:
#     name: sonarr
#   /home/fjavidcr/docker/jackett/config:
#     name: jackett
#   /home/fjavidcr/docker/lidarr/config:
#     name: lidarr
#   /home/fjavidcr/docker/ombi/config:
#     name: ombi
