version: '2.7'
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - ~/docker/radarr/config:/config
      - /media/pi/wd500/torrentbox/multimedia/radarr:/mnt/multimedia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - /home/pi/docker/sonarr/config:/config
      - /media/pi/wd500/torrentbox/multimedia/sonarr:/mnt/multimedia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid

  jackett:
    image: linuxserver/jackett
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - /home/pi/docker/jackett/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/pi/docker/lidarr/config:/config
      - /media/pi/wd500/torrentbox/multimedia/lidarr:/mnt/multimedia
    ports:
      - 8686:8686
    restart: unless-stopped

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - BASE_URL=/ #optional
    volumes:
      - /home/pi/docker/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped

# volumes:
#   /home/pi/docker/radarr/config:
#     name: radarr
#   /home/pi/docker/sonarr/config:
#     name: sonarr
#   /home/pi/docker/jackett/config:
#     name: jackett
#   /home/pi/docker/lidarr/config:
#     name: lidarr
#   /home/pi/docker/ombi/config:
#     name: ombi
