version: '2.7'
services:
  radarr:
    image: linuxserver/radarr:preview
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - ~/docker/radarr/config:/config
      - multimedia:/mnt/multimedia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid

  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - ~/docker/sonarr/config:/config
      - multimedia:/mnt/multimedia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - ~/docker/jackett/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ~/docker/lidarr/config:/config
      - multimedia:/mnt/multimedia
    ports:
      - 8686:8686
    restart: unless-stopped

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - BASE_URL=/ #optional
    volumes:
      - ~/docker/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped

volumes:
  ~/docker/radarr/config:
    name: radarr
  ~/docker/sonarr/config:
    name: sonarr
  ~/docker/jackett/config:
    name: jackett
  ~/docker/lidarr/config:
    name: lidarr
  ~/docker/ombi/config:
    name: ombi